#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAdministrationSystem
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CollegeDB")]
	public partial class CollegeDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    partial void InsertStudent(Student instance);
    partial void UpdateStudent(Student instance);
    partial void DeleteStudent(Student instance);
    partial void InsertTransaction(Transaction instance);
    partial void UpdateTransaction(Transaction instance);
    partial void DeleteTransaction(Transaction instance);
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    #endregion
		
		public CollegeDBDataContext() : 
				base(global::StudentAdministrationSystem.Properties.Settings.Default.CollegeDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public CollegeDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CollegeDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CollegeDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CollegeDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
		
		public System.Data.Linq.Table<Student> Students
		{
			get
			{
				return this.GetTable<Student>();
			}
		}
		
		public System.Data.Linq.Table<Transaction> Transactions
		{
			get
			{
				return this.GetTable<Transaction>();
			}
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QueryAllStudents")]
		public ISingleResult<QueryAllStudentsResult> QueryAllStudents()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<QueryAllStudentsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QueryByFirstname")]
		public ISingleResult<QueryByFirstnameResult> QueryByFirstname([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string fname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fname);
			return ((ISingleResult<QueryByFirstnameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QueryByGender")]
		public ISingleResult<QueryByGenderResult> QueryByGender([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string gender)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gender);
			return ((ISingleResult<QueryByGenderResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QueryByMiddlename")]
		public ISingleResult<QueryByMiddlenameResult> QueryByMiddlename([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string mname)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mname);
			return ((ISingleResult<QueryByMiddlenameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QueryByStudentNumber")]
		public ISingleResult<QueryByStudentNumberResult> QueryByStudentNumber([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string stdNum)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), stdNum);
			return ((ISingleResult<QueryByStudentNumberResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QueryBySurname")]
		public ISingleResult<QueryBySurnameResult> QueryBySurname([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((ISingleResult<QueryBySurnameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QueryByYear")]
		public ISingleResult<QueryByYearResult> QueryByYear([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string year)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), year);
			return ((ISingleResult<QueryByYearResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.QueryByCourse")]
		public ISingleResult<QueryByCourseResult> QueryByCourse([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string course)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), course);
			return ((ISingleResult<QueryByCourseResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Payment_Insert")]
		public int Payment_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RefNum", DbType="Int")] System.Nullable<int> refNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StdNum", DbType="Int")] System.Nullable<int> stdNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TDate", DbType="Date")] System.Nullable<System.DateTime> tDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TName", DbType="VarChar(50)")] string tName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TPaid", DbType="Decimal(18,0)")] System.Nullable<decimal> tPaid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bal", DbType="Decimal(18,0)")] System.Nullable<decimal> bal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TAmount", DbType="Decimal(18,0)")] System.Nullable<decimal> tAmount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), refNum, stdNum, tDate, tName, tPaid, bal, tAmount);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ReversePayment")]
		public int ReversePayment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="RefNum", DbType="Int")] System.Nullable<int> refNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StdNum", DbType="Int")] System.Nullable<int> stdNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TDate", DbType="Date")] System.Nullable<System.DateTime> tDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TName", DbType="VarChar(50)")] string tName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TPaid", DbType="Decimal(18,0)")] System.Nullable<decimal> tPaid, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Bal", DbType="Decimal(18,0)")] System.Nullable<decimal> bal, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TAmount", DbType="Decimal(18,0)")] System.Nullable<decimal> tAmount)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), refNum, stdNum, tDate, tName, tPaid, bal, tAmount);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Students")]
	public partial class Student : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Student_Number;
		
		private string _Firstname;
		
		private string _Middlename;
		
		private string _Surname;
		
		private System.DateTime _Date_Of_Birth;
		
		private string _Gender;
		
		private System.DateTime _Registration_Date;
		
		private string _Course;
		
		private decimal _Course_Fee;
		
		private EntitySet<Transaction> _Transactions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudent_NumberChanging(int value);
    partial void OnStudent_NumberChanged();
    partial void OnFirstnameChanging(string value);
    partial void OnFirstnameChanged();
    partial void OnMiddlenameChanging(string value);
    partial void OnMiddlenameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnDate_Of_BirthChanging(System.DateTime value);
    partial void OnDate_Of_BirthChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnRegistration_DateChanging(System.DateTime value);
    partial void OnRegistration_DateChanged();
    partial void OnCourseChanging(string value);
    partial void OnCourseChanged();
    partial void OnCourse_FeeChanging(decimal value);
    partial void OnCourse_FeeChanged();
    #endregion
		
		public Student()
		{
			this._Transactions = new EntitySet<Transaction>(new Action<Transaction>(this.attach_Transactions), new Action<Transaction>(this.detach_Transactions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Number", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Student_Number
		{
			get
			{
				return this._Student_Number;
			}
			set
			{
				if ((this._Student_Number != value))
				{
					this.OnStudent_NumberChanging(value);
					this.SendPropertyChanging();
					this._Student_Number = value;
					this.SendPropertyChanged("Student_Number");
					this.OnStudent_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this.OnFirstnameChanging(value);
					this.SendPropertyChanging();
					this._Firstname = value;
					this.SendPropertyChanged("Firstname");
					this.OnFirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Middlename", DbType="VarChar(50)")]
		public string Middlename
		{
			get
			{
				return this._Middlename;
			}
			set
			{
				if ((this._Middlename != value))
				{
					this.OnMiddlenameChanging(value);
					this.SendPropertyChanging();
					this._Middlename = value;
					this.SendPropertyChanged("Middlename");
					this.OnMiddlenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_Of_Birth", DbType="Date NOT NULL")]
		public System.DateTime Date_Of_Birth
		{
			get
			{
				return this._Date_Of_Birth;
			}
			set
			{
				if ((this._Date_Of_Birth != value))
				{
					this.OnDate_Of_BirthChanging(value);
					this.SendPropertyChanging();
					this._Date_Of_Birth = value;
					this.SendPropertyChanged("Date_Of_Birth");
					this.OnDate_Of_BirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registration_Date", DbType="Date NOT NULL")]
		public System.DateTime Registration_Date
		{
			get
			{
				return this._Registration_Date;
			}
			set
			{
				if ((this._Registration_Date != value))
				{
					this.OnRegistration_DateChanging(value);
					this.SendPropertyChanging();
					this._Registration_Date = value;
					this.SendPropertyChanged("Registration_Date");
					this.OnRegistration_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this.OnCourseChanging(value);
					this.SendPropertyChanging();
					this._Course = value;
					this.SendPropertyChanged("Course");
					this.OnCourseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course_Fee", DbType="Money NOT NULL")]
		public decimal Course_Fee
		{
			get
			{
				return this._Course_Fee;
			}
			set
			{
				if ((this._Course_Fee != value))
				{
					this.OnCourse_FeeChanging(value);
					this.SendPropertyChanging();
					this._Course_Fee = value;
					this.SendPropertyChanged("Course_Fee");
					this.OnCourse_FeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Transaction", Storage="_Transactions", ThisKey="Student_Number", OtherKey="Student_Number")]
		public EntitySet<Transaction> Transactions
		{
			get
			{
				return this._Transactions;
			}
			set
			{
				this._Transactions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Transactions(Transaction entity)
		{
			this.SendPropertyChanging();
			entity.Student = this;
		}
		
		private void detach_Transactions(Transaction entity)
		{
			this.SendPropertyChanging();
			entity.Student = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Transactions")]
	public partial class Transaction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Reference_Number;
		
		private int _Student_Number;
		
		private System.DateTime _Transaction_Date;
		
		private string _Transaction_Name;
		
		private decimal _Transaction_Amount;
		
		private decimal _Total_Paid;
		
		private System.Nullable<bool> _Reversal;
		
		private decimal _Balance;
		
		private EntityRef<Student> _Student;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReference_NumberChanging(int value);
    partial void OnReference_NumberChanged();
    partial void OnStudent_NumberChanging(int value);
    partial void OnStudent_NumberChanged();
    partial void OnTransaction_DateChanging(System.DateTime value);
    partial void OnTransaction_DateChanged();
    partial void OnTransaction_NameChanging(string value);
    partial void OnTransaction_NameChanged();
    partial void OnTransaction_AmountChanging(decimal value);
    partial void OnTransaction_AmountChanged();
    partial void OnTotal_PaidChanging(decimal value);
    partial void OnTotal_PaidChanged();
    partial void OnReversalChanging(System.Nullable<bool> value);
    partial void OnReversalChanged();
    partial void OnBalanceChanging(decimal value);
    partial void OnBalanceChanged();
    #endregion
		
		public Transaction()
		{
			this._Student = default(EntityRef<Student>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reference_Number", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Reference_Number
		{
			get
			{
				return this._Reference_Number;
			}
			set
			{
				if ((this._Reference_Number != value))
				{
					this.OnReference_NumberChanging(value);
					this.SendPropertyChanging();
					this._Reference_Number = value;
					this.SendPropertyChanged("Reference_Number");
					this.OnReference_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Number", DbType="Int NOT NULL")]
		public int Student_Number
		{
			get
			{
				return this._Student_Number;
			}
			set
			{
				if ((this._Student_Number != value))
				{
					if (this._Student.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnStudent_NumberChanging(value);
					this.SendPropertyChanging();
					this._Student_Number = value;
					this.SendPropertyChanged("Student_Number");
					this.OnStudent_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_Date", DbType="Date NOT NULL")]
		public System.DateTime Transaction_Date
		{
			get
			{
				return this._Transaction_Date;
			}
			set
			{
				if ((this._Transaction_Date != value))
				{
					this.OnTransaction_DateChanging(value);
					this.SendPropertyChanging();
					this._Transaction_Date = value;
					this.SendPropertyChanged("Transaction_Date");
					this.OnTransaction_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Transaction_Name
		{
			get
			{
				return this._Transaction_Name;
			}
			set
			{
				if ((this._Transaction_Name != value))
				{
					this.OnTransaction_NameChanging(value);
					this.SendPropertyChanging();
					this._Transaction_Name = value;
					this.SendPropertyChanged("Transaction_Name");
					this.OnTransaction_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transaction_Amount", DbType="Money NOT NULL")]
		public decimal Transaction_Amount
		{
			get
			{
				return this._Transaction_Amount;
			}
			set
			{
				if ((this._Transaction_Amount != value))
				{
					this.OnTransaction_AmountChanging(value);
					this.SendPropertyChanging();
					this._Transaction_Amount = value;
					this.SendPropertyChanged("Transaction_Amount");
					this.OnTransaction_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Paid", DbType="Money NOT NULL")]
		public decimal Total_Paid
		{
			get
			{
				return this._Total_Paid;
			}
			set
			{
				if ((this._Total_Paid != value))
				{
					this.OnTotal_PaidChanging(value);
					this.SendPropertyChanging();
					this._Total_Paid = value;
					this.SendPropertyChanged("Total_Paid");
					this.OnTotal_PaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reversal", DbType="Bit")]
		public System.Nullable<bool> Reversal
		{
			get
			{
				return this._Reversal;
			}
			set
			{
				if ((this._Reversal != value))
				{
					this.OnReversalChanging(value);
					this.SendPropertyChanging();
					this._Reversal = value;
					this.SendPropertyChanged("Reversal");
					this.OnReversalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Money NOT NULL")]
		public decimal Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this.OnBalanceChanging(value);
					this.SendPropertyChanging();
					this._Balance = value;
					this.SendPropertyChanged("Balance");
					this.OnBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Transaction", Storage="_Student", ThisKey="Student_Number", OtherKey="Student_Number", IsForeignKey=true)]
		public Student Student
		{
			get
			{
				return this._Student.Entity;
			}
			set
			{
				Student previousValue = this._Student.Entity;
				if (((previousValue != value) 
							|| (this._Student.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student.Entity = null;
						previousValue.Transactions.Remove(this);
					}
					this._Student.Entity = value;
					if ((value != null))
					{
						value.Transactions.Add(this);
						this._Student_Number = value.Student_Number;
					}
					else
					{
						this._Student_Number = default(int);
					}
					this.SendPropertyChanged("Student");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Pin;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPinChanging(string value);
    partial void OnPinChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pin", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Pin
		{
			get
			{
				return this._Pin;
			}
			set
			{
				if ((this._Pin != value))
				{
					this.OnPinChanging(value);
					this.SendPropertyChanging();
					this._Pin = value;
					this.SendPropertyChanged("Pin");
					this.OnPinChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class QueryAllStudentsResult
	{
		
		private System.Nullable<int> _Student_Number;
		
		private string _Firstname;
		
		private string _Middlename;
		
		private string _Surname;
		
		private string _Gender;
		
		private string _Course;
		
		private System.Nullable<System.DateTime> _Registration_Date;
		
		private System.Nullable<decimal> _Course_Fee;
		
		private System.Nullable<decimal> _Total_Paid;
		
		private System.Nullable<decimal> _Balance;
		
		public QueryAllStudentsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Number", DbType="Int")]
		public System.Nullable<int> Student_Number
		{
			get
			{
				return this._Student_Number;
			}
			set
			{
				if ((this._Student_Number != value))
				{
					this._Student_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(50)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Middlename", DbType="VarChar(50)")]
		public string Middlename
		{
			get
			{
				return this._Middlename;
			}
			set
			{
				if ((this._Middlename != value))
				{
					this._Middlename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="VarChar(50)")]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this._Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registration_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Registration_Date
		{
			get
			{
				return this._Registration_Date;
			}
			set
			{
				if ((this._Registration_Date != value))
				{
					this._Registration_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course_Fee", DbType="Money")]
		public System.Nullable<decimal> Course_Fee
		{
			get
			{
				return this._Course_Fee;
			}
			set
			{
				if ((this._Course_Fee != value))
				{
					this._Course_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Paid", DbType="Money")]
		public System.Nullable<decimal> Total_Paid
		{
			get
			{
				return this._Total_Paid;
			}
			set
			{
				if ((this._Total_Paid != value))
				{
					this._Total_Paid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Money")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
	
	public partial class QueryByFirstnameResult
	{
		
		private System.Nullable<int> _Student_Number;
		
		private string _Firstname;
		
		private string _Middlename;
		
		private string _Surname;
		
		private string _Gender;
		
		private string _Course;
		
		private System.Nullable<System.DateTime> _Registration_Date;
		
		private System.Nullable<decimal> _Course_Fee;
		
		private System.Nullable<decimal> _Total_Paid;
		
		private System.Nullable<decimal> _Balance;
		
		public QueryByFirstnameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Number", DbType="Int")]
		public System.Nullable<int> Student_Number
		{
			get
			{
				return this._Student_Number;
			}
			set
			{
				if ((this._Student_Number != value))
				{
					this._Student_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(50)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Middlename", DbType="VarChar(50)")]
		public string Middlename
		{
			get
			{
				return this._Middlename;
			}
			set
			{
				if ((this._Middlename != value))
				{
					this._Middlename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="VarChar(50)")]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this._Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registration_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Registration_Date
		{
			get
			{
				return this._Registration_Date;
			}
			set
			{
				if ((this._Registration_Date != value))
				{
					this._Registration_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course_Fee", DbType="Money")]
		public System.Nullable<decimal> Course_Fee
		{
			get
			{
				return this._Course_Fee;
			}
			set
			{
				if ((this._Course_Fee != value))
				{
					this._Course_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Paid", DbType="Money")]
		public System.Nullable<decimal> Total_Paid
		{
			get
			{
				return this._Total_Paid;
			}
			set
			{
				if ((this._Total_Paid != value))
				{
					this._Total_Paid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Money")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
	
	public partial class QueryByGenderResult
	{
		
		private System.Nullable<int> _Student_Number;
		
		private string _Firstname;
		
		private string _Middlename;
		
		private string _Surname;
		
		private string _Gender;
		
		private string _Course;
		
		private System.Nullable<System.DateTime> _Registration_Date;
		
		private System.Nullable<decimal> _Course_Fee;
		
		private System.Nullable<decimal> _Total_Paid;
		
		private System.Nullable<decimal> _Balance;
		
		public QueryByGenderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Number", DbType="Int")]
		public System.Nullable<int> Student_Number
		{
			get
			{
				return this._Student_Number;
			}
			set
			{
				if ((this._Student_Number != value))
				{
					this._Student_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(50)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Middlename", DbType="VarChar(50)")]
		public string Middlename
		{
			get
			{
				return this._Middlename;
			}
			set
			{
				if ((this._Middlename != value))
				{
					this._Middlename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="VarChar(50)")]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this._Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registration_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Registration_Date
		{
			get
			{
				return this._Registration_Date;
			}
			set
			{
				if ((this._Registration_Date != value))
				{
					this._Registration_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course_Fee", DbType="Money")]
		public System.Nullable<decimal> Course_Fee
		{
			get
			{
				return this._Course_Fee;
			}
			set
			{
				if ((this._Course_Fee != value))
				{
					this._Course_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Paid", DbType="Money")]
		public System.Nullable<decimal> Total_Paid
		{
			get
			{
				return this._Total_Paid;
			}
			set
			{
				if ((this._Total_Paid != value))
				{
					this._Total_Paid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Money")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
	
	public partial class QueryByMiddlenameResult
	{
		
		private System.Nullable<int> _Student_Number;
		
		private string _Firstname;
		
		private string _Middlename;
		
		private string _Surname;
		
		private string _Gender;
		
		private string _Course;
		
		private System.Nullable<System.DateTime> _Registration_Date;
		
		private System.Nullable<decimal> _Course_Fee;
		
		private System.Nullable<decimal> _Total_Paid;
		
		private System.Nullable<decimal> _Balance;
		
		public QueryByMiddlenameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Number", DbType="Int")]
		public System.Nullable<int> Student_Number
		{
			get
			{
				return this._Student_Number;
			}
			set
			{
				if ((this._Student_Number != value))
				{
					this._Student_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(50)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Middlename", DbType="VarChar(50)")]
		public string Middlename
		{
			get
			{
				return this._Middlename;
			}
			set
			{
				if ((this._Middlename != value))
				{
					this._Middlename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="VarChar(50)")]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this._Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registration_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Registration_Date
		{
			get
			{
				return this._Registration_Date;
			}
			set
			{
				if ((this._Registration_Date != value))
				{
					this._Registration_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course_Fee", DbType="Money")]
		public System.Nullable<decimal> Course_Fee
		{
			get
			{
				return this._Course_Fee;
			}
			set
			{
				if ((this._Course_Fee != value))
				{
					this._Course_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Paid", DbType="Money")]
		public System.Nullable<decimal> Total_Paid
		{
			get
			{
				return this._Total_Paid;
			}
			set
			{
				if ((this._Total_Paid != value))
				{
					this._Total_Paid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Money")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
	
	public partial class QueryByStudentNumberResult
	{
		
		private System.Nullable<int> _Student_Number;
		
		private string _Firstname;
		
		private string _Middlename;
		
		private string _Surname;
		
		private string _Gender;
		
		private string _Course;
		
		private System.Nullable<System.DateTime> _Registration_Date;
		
		private System.Nullable<decimal> _Course_Fee;
		
		private System.Nullable<decimal> _Total_Paid;
		
		private System.Nullable<decimal> _Balance;
		
		public QueryByStudentNumberResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Number", DbType="Int")]
		public System.Nullable<int> Student_Number
		{
			get
			{
				return this._Student_Number;
			}
			set
			{
				if ((this._Student_Number != value))
				{
					this._Student_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(50)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Middlename", DbType="VarChar(50)")]
		public string Middlename
		{
			get
			{
				return this._Middlename;
			}
			set
			{
				if ((this._Middlename != value))
				{
					this._Middlename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="VarChar(50)")]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this._Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registration_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Registration_Date
		{
			get
			{
				return this._Registration_Date;
			}
			set
			{
				if ((this._Registration_Date != value))
				{
					this._Registration_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course_Fee", DbType="Money")]
		public System.Nullable<decimal> Course_Fee
		{
			get
			{
				return this._Course_Fee;
			}
			set
			{
				if ((this._Course_Fee != value))
				{
					this._Course_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Paid", DbType="Money")]
		public System.Nullable<decimal> Total_Paid
		{
			get
			{
				return this._Total_Paid;
			}
			set
			{
				if ((this._Total_Paid != value))
				{
					this._Total_Paid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Money")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
	
	public partial class QueryBySurnameResult
	{
		
		private System.Nullable<int> _Student_Number;
		
		private string _Firstname;
		
		private string _Middlename;
		
		private string _Surname;
		
		private string _Gender;
		
		private string _Course;
		
		private System.Nullable<System.DateTime> _Registration_Date;
		
		private System.Nullable<decimal> _Course_Fee;
		
		private System.Nullable<decimal> _Total_Paid;
		
		private System.Nullable<decimal> _Balance;
		
		public QueryBySurnameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Number", DbType="Int")]
		public System.Nullable<int> Student_Number
		{
			get
			{
				return this._Student_Number;
			}
			set
			{
				if ((this._Student_Number != value))
				{
					this._Student_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(50)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Middlename", DbType="VarChar(50)")]
		public string Middlename
		{
			get
			{
				return this._Middlename;
			}
			set
			{
				if ((this._Middlename != value))
				{
					this._Middlename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="VarChar(50)")]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this._Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registration_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Registration_Date
		{
			get
			{
				return this._Registration_Date;
			}
			set
			{
				if ((this._Registration_Date != value))
				{
					this._Registration_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course_Fee", DbType="Money")]
		public System.Nullable<decimal> Course_Fee
		{
			get
			{
				return this._Course_Fee;
			}
			set
			{
				if ((this._Course_Fee != value))
				{
					this._Course_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Paid", DbType="Money")]
		public System.Nullable<decimal> Total_Paid
		{
			get
			{
				return this._Total_Paid;
			}
			set
			{
				if ((this._Total_Paid != value))
				{
					this._Total_Paid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Money")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
	
	public partial class QueryByYearResult
	{
		
		private System.Nullable<int> _Student_Number;
		
		private string _Firstname;
		
		private string _Middlename;
		
		private string _Surname;
		
		private string _Gender;
		
		private string _Course;
		
		private System.Nullable<System.DateTime> _Registration_Date;
		
		private System.Nullable<decimal> _Course_Fee;
		
		private System.Nullable<decimal> _Total_Paid;
		
		private System.Nullable<decimal> _Balance;
		
		public QueryByYearResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Number", DbType="Int")]
		public System.Nullable<int> Student_Number
		{
			get
			{
				return this._Student_Number;
			}
			set
			{
				if ((this._Student_Number != value))
				{
					this._Student_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(50)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Middlename", DbType="VarChar(50)")]
		public string Middlename
		{
			get
			{
				return this._Middlename;
			}
			set
			{
				if ((this._Middlename != value))
				{
					this._Middlename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="VarChar(50)")]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this._Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registration_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Registration_Date
		{
			get
			{
				return this._Registration_Date;
			}
			set
			{
				if ((this._Registration_Date != value))
				{
					this._Registration_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course_Fee", DbType="Money")]
		public System.Nullable<decimal> Course_Fee
		{
			get
			{
				return this._Course_Fee;
			}
			set
			{
				if ((this._Course_Fee != value))
				{
					this._Course_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Paid", DbType="Money")]
		public System.Nullable<decimal> Total_Paid
		{
			get
			{
				return this._Total_Paid;
			}
			set
			{
				if ((this._Total_Paid != value))
				{
					this._Total_Paid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Money")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
	
	public partial class QueryByCourseResult
	{
		
		private System.Nullable<int> _Student_Number;
		
		private string _Firstname;
		
		private string _Middlename;
		
		private string _Surname;
		
		private string _Gender;
		
		private string _Course;
		
		private System.Nullable<System.DateTime> _Registration_Date;
		
		private System.Nullable<decimal> _Course_Fee;
		
		private System.Nullable<decimal> _Total_Paid;
		
		private System.Nullable<decimal> _Balance;
		
		public QueryByCourseResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Student_Number", DbType="Int")]
		public System.Nullable<int> Student_Number
		{
			get
			{
				return this._Student_Number;
			}
			set
			{
				if ((this._Student_Number != value))
				{
					this._Student_Number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(50)")]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this._Firstname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Middlename", DbType="VarChar(50)")]
		public string Middlename
		{
			get
			{
				return this._Middlename;
			}
			set
			{
				if ((this._Middlename != value))
				{
					this._Middlename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50)")]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this._Surname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(50)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this._Gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course", DbType="VarChar(50)")]
		public string Course
		{
			get
			{
				return this._Course;
			}
			set
			{
				if ((this._Course != value))
				{
					this._Course = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Registration_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Registration_Date
		{
			get
			{
				return this._Registration_Date;
			}
			set
			{
				if ((this._Registration_Date != value))
				{
					this._Registration_Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Course_Fee", DbType="Money")]
		public System.Nullable<decimal> Course_Fee
		{
			get
			{
				return this._Course_Fee;
			}
			set
			{
				if ((this._Course_Fee != value))
				{
					this._Course_Fee = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Paid", DbType="Money")]
		public System.Nullable<decimal> Total_Paid
		{
			get
			{
				return this._Total_Paid;
			}
			set
			{
				if ((this._Total_Paid != value))
				{
					this._Total_Paid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Money")]
		public System.Nullable<decimal> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
